# Generated by Django 4.1.5 on 2023-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='bought',
            field=models.IntegerField(default=0),
        ),
    ]
